language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
install:
  - pip install pandas
  - pip install coveralls
script:
  - coverage run -m unittest vcf2tped
after_success:
  - coveralls
